<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\V0XMacroRecorder.Core\V0XMacroRecorder.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Interop.UIAutomationClient" Version="10.19041.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.11.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.12" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="V0XMacroRecorder.Tests" />
  </ItemGroup>

</Project>
